// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Send is the golang structure of table co_send for DAO operations like Where/Data.
type Send struct {
	g.Meta        `orm:"table:co_send, do:true"`
	Id            interface{} //
	Title         interface{} //
	MessageId     interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
	DeletedAt     *gtime.Time //
	SendModel     interface{} //
	SendServerId  interface{} //
	DispatchModel interface{} //
	Status        interface{} //
	SendListCount interface{} //
	SuccessCount  interface{} //
}
