// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SendList is the golang structure of table co_send_list for DAO operations like Where/Data.
type SendList struct {
	g.Meta       `orm:"table:co_send_list, do:true"`
	Id           interface{} //
	SendId       interface{} //
	Receive      interface{} //
	Status       interface{} //
	SendServerId interface{} //
}
