// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package co_dao

import (
	"github.com/jack353249002/exam-message-send-modules/co_model/co_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type SendListDao = dao_interface.TIDao[internal.SendListColumns]

func NewSendList(dao ...dao_interface.IDao) SendListDao {
	return (SendListDao)(internal.NewSendListDao(dao...))
}

var (
	SendList = NewSendList()
)
