// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

// SendList is the golang structure for table send_list.
type SendList struct {
	Id           int    `json:"id"           description:""`
	SendId       int    `json:"sendId"       description:""`
	Receive      string `json:"receive"      description:""`
	Status       int    `json:"status"       description:""`
	SendServerId int    `json:"sendServerId" description:""`
}
