// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package co_entity

// SmtpServer is the golang structure for table smtp_server.
type SmtpServer struct {
	Id             int    `json:"id"             description:""`
	SmtpServer     string `json:"smtpServer"     description:""`
	SmtpPassword   string `json:"smtpPassword"   description:""`
	Title          string `json:"title"          description:""`
	SmtpSendEmail  string `json:"smtpSendEmail"  description:""`
	Port           int    `json:"port"           description:""`
	MaxConcurrency int    `json:"maxConcurrency" description:""`
}
